# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CasaPassword/CasaPasswordRepositoryStore.git'
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/ModularizationTest/PrivatePods.git'

target '__ProjectName__' do
 
end
